<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ResourceStudio.Windows</AssemblyName>
    <RootNamespace>ResourceStudio.Windows</RootNamespace>
    <ApplicationIcon>Assets\resource-studio.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\resource-studio.ico" />
    <Resource Include="Assets\resource-studio-icon-16.png" />
    <Resource Include="Assets\resource-studio-icon-32.png" />
    <Resource Include="Assets\resource-studio-icon-64.png" />
  </ItemGroup>
</Project>
